export const DISPATCH_LIST_SUCCESS = "DISPATCH_LIST_SUCCESS";
export const DISPATCH_LIST_REQUEST = "DISPATCH_LIST_REQUEST";
export const DISPATCH_LIST_FAIL = "DISPATCH_LIST_FAIL";

export const DISPATCH_DETAILS_REQUEST = "DISPATCH_DETAILS_REQUEST";
export const DISPATCH_DETAILS_SUCCESS = "DISPATCH_DETAILS_SUCCESS";
export const DISPATCH_DETAILS_FAIL = "DISPATCH_DETAILS_FAIL";

export const DISPATCH_CREATE_REQUEST = "DISPATCH_CREATE_REQUEST";
export const DISPATCH_CREATE_SUCCESS = "DISPATCH_CREATE_SUCCESS";
export const DISPATCH_CREATE_FAIL = "DISPATCH_CREATE_FAIL";
export const DISPATCH_CREATE_RESET = "DISPATCH_CREATE_RESET";

export const DISPATCH_UPDATE_REQUEST = "DISPATCH_UPDATE_REQUEST";
export const DISPATCH_UPDATE_SUCCESS = "DISPATCH_UPDATE_SUCCESS";
export const DISPATCH_UPDATE_FAIL = "DISPATCH_UPDATE_FAIL";
export const DISPATCH_UPDATE_RESET = "DISPATCH_UPDATE_RESET";

export const DISPATCH_DELETE_REQUEST = "DISPATCH_DELETE_REQUEST";
export const DISPATCH_DELETE_SUCCESS = "DISPATCH_DELETE_SUCCESS";
export const DISPATCH_DELETE_FAIL = "DISPATCH_DELETE_FAIL";

export const COOKED_LIST_SUCCESS = "COOKED_LIST_SUCCESS";
export const COOKED_LIST_REQUEST = "COOKED_LIST_REQUEST";
export const COOKED_LIST_FAIL = "COOKED_LIST_FAIL";

export const COOKED_DETAILS_REQUEST = "COOKED_DETAILS_REQUEST";
export const COOKED_DETAILS_SUCCESS = "COOKED_DETAILS_SUCCESS";
export const COOKED_DETAILS_FAIL = "COOKED_DETAILS_FAIL";

export const COOKED_CREATE_REQUEST = "COOKED_CREATE_REQUEST";
export const COOKED_CREATE_SUCCESS = "COOKED_CREATE_SUCCESS";
export const COOKED_CREATE_FAIL = "COOKED_CREATE_FAIL";
export const COOKED_CREATE_RESET = "COOKED_CREATE_RESET";

export const COOKED_UPDATE_REQUEST = "COOKED_UPDATE_REQUEST";
export const COOKED_UPDATE_SUCCESS = "COOKED_UPDATE_SUCCESS";
export const COOKED_UPDATE_FAIL = "COOKED_UPDATE_FAIL";
export const COOKED_UPDATE_RESET = "COOKED_UPDATE_RESET";

export const COOKED_DELETE_REQUEST = "COOKED_DELETE_REQUEST";
export const COOKED_DELETE_SUCCESS = "COOKED_DELETE_SUCCESS";
export const COOKED_DELETE_FAIL = "COOKED_DELETE_FAIL";
