export const HUB_LIST_SUCCESS = "HUB_LIST_SUCCESS";
export const HUB_LIST_REQUEST = "HUB_LIST_REQUEST";
export const HUB_LIST_FAIL = "HUB_LIST_FAIL";

export const HUB_DETAILS_REQUEST = "HUB_DETAILS_REQUEST";
export const HUB_DETAILS_SUCCESS = "HUB_DETAILS_SUCCESS";
export const HUB_DETAILS_FAIL = "HUB_DETAILS_FAIL";

export const HUB_CREATE_REQUEST = "HUB_CREATE_REQUEST";
export const HUB_CREATE_SUCCESS = "HUB_CREATE_SUCCESS";
export const HUB_CREATE_FAIL = "HUB_CREATE_FAIL";
export const HUB_CREATE_RESET = "HUB_CREATE_RESET";

export const HUB_UPDATE_REQUEST = "HUB_UPDATE_REQUEST";
export const HUB_UPDATE_SUCCESS = "HUB_UPDATE_SUCCESS";
export const HUB_UPDATE_FAIL = "HUB_UPDATE_FAIL";
export const HUB_UPDATE_RESET = "HUB_UPDATE_RESET";

export const HUB_DELETE_REQUEST = "HUB_DELETE_REQUEST";
export const HUB_DELETE_SUCCESS = "HUB_DELETE_SUCCESS";
export const HUB_DELETE_FAIL = "HUB_DELETE_FAIL";

export const DELIVERY_PARTNER_LIST_SUCCESS = "DELIVERY_PARTNER_LIST_SUCCESS";
export const DELIVERY_PARTNER_LIST_REQUEST = "DELIVERY_PARTNER_LIST_REQUEST";
export const DELIVERY_PARTNER_LIST_FAIL = "DELIVERY_PARTNER_LIST_FAIL";

export const DELIVERY_PARTNER_DETAILS_REQUEST =
  "DELIVERY_PARTNER_DETAILS_REQUEST";
export const DELIVERY_PARTNER_DETAILS_SUCCESS =
  "DELIVERY_PARTNER_DETAILS_SUCCESS";
export const DELIVERY_PARTNER_DETAILS_FAIL = "DELIVERY_PARTNER_DETAILS_FAIL";

export const DELIVERY_PARTNER_CREATE_REQUEST =
  "DELIVERY_PARTNER_CREATE_REQUEST";
export const DELIVERY_PARTNER_CREATE_SUCCESS =
  "DELIVERY_PARTNER_CREATE_SUCCESS";
export const DELIVERY_PARTNER_CREATE_FAIL = "DELIVERY_PARTNER_CREATE_FAIL";
export const DELIVERY_PARTNER_CREATE_RESET = "DELIVERY_PARTNER_CREATE_RESET";

export const DELIVERY_PARTNER_UPDATE_REQUEST =
  "DELIVERY_PARTNER_UPDATE_REQUEST";
export const DELIVERY_PARTNER_UPDATE_SUCCESS =
  "DELIVERY_PARTNER_UPDATE_SUCCESS";
export const DELIVERY_PARTNER_UPDATE_FAIL = "DELIVERY_PARTNER_UPDATE_FAIL";
export const DELIVERY_PARTNER_UPDATE_RESET = "DELIVERY_PARTNER_UPDATE_RESET";

export const DELIVERY_PARTNER_DELETE_REQUEST =
  "DELIVERY_PARTNER_DELETE_REQUEST";
export const DELIVERY_PARTNER_DELETE_SUCCESS =
  "DELIVERY_PARTNER_DELETE_SUCCESS";
export const DELIVERY_PARTNER_DELETE_FAIL = "DELIVERY_PARTNER_DELETE_FAIL";
