export const SLIDER_LIST_SUCCESS = "SLIDER_LIST_SUCCESS";
export const SLIDER_LIST_REQUEST = "SLIDER_LIST_REQUEST";
export const SLIDER_LIST_FAIL = "SLIDER_LIST_FAIL";

export const SLIDER_DETAILS_REQUEST = "SLIDER_DETAILS_REQUEST";
export const SLIDER_DETAILS_SUCCESS = "SLIDER_DETAILS_SUCCESS";
export const SLIDER_DETAILS_FAIL = "SLIDER_DETAILS_FAIL";

export const SLIDER_CREATE_REQUEST = "SLIDER_CREATE_REQUEST";
export const SLIDER_CREATE_SUCCESS = "SLIDER_CREATE_SUCCESS";
export const SLIDER_CREATE_FAIL = "SLIDER_CREATE_FAIL";
export const SLIDER_CREATE_RESET = "SLIDER_CREATE_RESET";

export const SLIDER_UPDATE_REQUEST = "SLIDER_UPDATE_REQUEST";
export const SLIDER_UPDATE_SUCCESS = "SLIDER_UPDATE_SUCCESS";
export const SLIDER_UPDATE_FAIL = "SLIDER_UPDATE_FAIL";
export const SLIDER_UPDATE_RESET = "SLIDER_UPDATE_RESET";

export const SLIDER_DELETE_REQUEST = "SLIDER_DELETE_REQUEST";
export const SLIDER_DELETE_SUCCESS = "SLIDER_DELETE_SUCCESS";
export const SLIDER_DELETE_FAIL = "SLIDER_DELETE_FAIL";

export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL";

export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST";
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS";
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL";

export const BLOG_CREATE_REQUEST = "BLOG_CREATE_REQUEST";
export const BLOG_CREATE_SUCCESS = "BLOG_CREATE_SUCCESS";
export const BLOG_CREATE_FAIL = "BLOG_CREATE_FAIL";
export const BLOG_CREATE_RESET = "BLOG_CREATE_RESET";

export const BLOG_UPDATE_REQUEST = "BLOG_UPDATE_REQUEST";
export const BLOG_UPDATE_SUCCESS = "BLOG_UPDATE_SUCCESS";
export const BLOG_UPDATE_FAIL = "BLOG_UPDATE_FAIL";
export const BLOG_UPDATE_RESET = "BLOG_UPDATE_RESET";

export const BLOG_DELETE_REQUEST = "BLOG_DELETE_REQUEST";
export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS";
export const BLOG_DELETE_FAIL = "BLOG_DELETE_FAIL";
